tuples = (9, 1, 6, 7, 8)
print(tuples)
print(tuples[:3])
print(tuples[2:])
print(tuples[:])
print(tuples[-1:-6:-2])
list1 = list(tuples)
list1.append("Hamza")
list1.insert(3, "ahamd")
list1.pop()
tuples = tuple(list1)
print(tuples)